config/routes.rb
Bioluminous::Application.routes.draw do
  root 'home#index'
  
  get 'index' => 'home#index'

  scope "games" do
    root to: "games#index", as: :games
    get "gather" => "games#gather", as: :gather
  end
  
  get "rp/libram" => "tabletop#libram", as: :libram

  get 'fos' => 'home#fos'

  get "insults" => 'insults#index'
  post "insults" => "insults#generate"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
  end
  
  def gather
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def fos
  end

  def gather
  end
end

app/controllers/insults_controller.rb
class InsultsController < ApplicationController
  include InsultsHelper

  # GET /insults
  def index
    @insult = fetch_insult
  end

  # POST /insults
  def generate
    if request.xhr?
      render text: fetch_insult
    else
      redirect_to action: 'index'
    end
  end

  private

  def fetch_insult
    insult = []
    insult << insult_list1[Random.rand(insult_list1.size)]
    insult << insult_list2[Random.rand(insult_list2.size)]
    insult << insult_list3[Random.rand(insult_list3.size)]
    insult.join ' '
  end
end

app/controllers/tabletop_controller.rb
class TabletopController < ApplicationController
  def libram
    @title = "Libram Auto-Roller"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/insults_helper.rb
module InsultsHelper

  @@insult_list1 = ['lazy',
                    'stupid',
                    'insecure',
                    'idiotic',
                    'slimy',
                    'slutty',
                    'smelly',
                    'pompous',
                    'Communist',
                    'dicknose',
                    'pie-eating',
                    'racist',
                    'elitist',
                    'white trash',
                    'drug-loving',
                    'butterface',
                    'tone deaf',
                    'ugly',
                    'creepy']

  @@insult_list2 = ['douche',
                     'ass',
                     'turd',
                     'rectum',
                     'butt',
                     'cock',
                     'shit',
                     'crotch',
                     'bitch',
                     'schlong',
                     'twat',
                     'prick',
                     'slut',
                     'taint',
                     'fuck',
                     'dick',
                     'boner',
                     'shart',
                     'nut',
                     'sphincter']

  @@insult_list3 = ['pilot',
                    'canoe',
                    'captain',
                    'pirate',
                    'hammer',
                    'knob',
                    'box',
                    'jockey',
                    'Nazi',
                    'waffle',
                    'goblin',
                    'blossom',
                    'biscuit',
                    'clown',
                    'socket',
                    'monster',
                    'hound',
                    'dragon',
                    'balloon',
                    'buffoon',
                    'muffin']

  def insult_list1
    @@insult_list1
  end

  def insult_list2
    @@insult_list2
  end

  def insult_list3
    @@insult_list3
  end

end

app/views/games/gather.html.erb
<h3 class="text-red">Gather</h3>

<p>A small 2D platformer/survival game. Attempt to collect the <span class="text-red">artifact</span> and return to the surface in one piece. It appears in a random location each time, so you might have to scour the whole cave complex in order to find it. But beware: the longer you dawdle, the more vicious monsters will appear and attempt to destroy you.</p>

<p>Source code is available <%= link_to "here", "https://github.com/rmtsukuru/Gather", target: "_blank" %></p>

<h4>Screenshots</h4>

<div class="screenshots">
    <div class="half">
        <%= image_tag "gather-screen0.png" %>
    </div>
    <div class="half">
        <%= image_tag "gather-screen1.png" %>
    </div>
    <div class="half">
        <%= image_tag "gather-screen3.png" %>
    </div>
    <div class="half">
        <%= image_tag "gather-screen6.png" %>
    </div>
    <div class="half">
        <%= image_tag "gather-screen4.png" %>
    </div>
    <div class="half">
        <%= image_tag "gather-screen7.png" %>
    </div>
</div>

<h4>Downloads</h4>

<p>
    <%= link_to "Windows 64-bit", "https://drive.google.com/open?id=0B8oXVbHh5bEwSmg0TWQ5N01TazQ", target: "_blank", class: "text-green" %> |
    <%= link_to "Linux 64-bit", "https://drive.google.com/open?id=0B8oXVbHh5bEwLXpoVW1qNm5qNVU", target: "_blank", class: "text-green" %> |
    <%= link_to "MacOS", "https://drive.google.com/open?id=0B8oXVbHh5bEwYXNST0xFWGF6bUE", target: "_blank", class: "text-green" %> |
    <%= link_to "Others", "https://drive.google.com/open?id=0B8oXVbHh5bEwUEJ5LXJOR2pMenM", target: "_blank", class: "text-green" %>
</p>

app/views/games/index.html.erb
<div class="center">
  <h2 class="text-green">Games</h2>
  <p><%= link_to "Gather", gather_path, class: "text-green" %></p>
  <p><%= link_to "Hunt", "https://rmtsukuru.itch.io/hunt", class: "text-green" %></p>
</div>

app/views/home/fos.html.erb
<h1>Fos</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse tristique, tellus ac tempus feugiat, ligula libero laoreet nisi, ac porta lectus lectus nec leo. Suspendisse vulputate felis eget pellentesque convallis. Vestibulum elementum suscipit justo, scelerisque venenatis ligula fermentum at. Maecenas tincidunt massa arcu, at pretium justo accumsan id. Sed tincidunt turpis at tortor vulputate, at rhoncus mi pretium. Praesent risus mauris, dapibus vel sollicitudin volutpat, iaculis vel quam. Aenean luctus elementum augue. Nunc ullamcorper tincidunt arcu at tempus. Curabitur non neque non ante facilisis facilisis eget ut dolor. Phasellus ac eros justo. Vivamus tortor dui, sodales vel mauris vel, imperdiet varius mauris. Integer vitae felis erat. Nulla volutpat tempor nibh, sollicitudin egestas nunc feugiat ac.</p>

app/views/home/index.html.erb
<div class="center">
  <h1 class="text-green">Biolumino.us</h1>
  <%= image_tag "viperfish_deadly_deep_predator4.jpg" %>
  <h2 class="text-green">Games</h2>
  <p><%= link_to "Gather", gather_path, class: "text-green" %></p>
  <p><%= link_to "Hunt", "https://rmtsukuru.itch.io/hunt", class: "text-green" %></p>
  <h2 class="text-green">Tabletop</h2>
  <%= link_to "Libram Auto-Roller", libram_path, class: "text-green" %>
</div>

app/views/insults/generate.html.erb
<h1>Insults#generate</h1>
<p>Find me in app/views/insults/generate.html.erb</p>

app/views/insults/index.html.erb
<div id="insults">
  <h1>The Ultimate Insult Creator</h1>
  <%= form_tag do %>
    <p id="result"><%= @insult %></p>
    <%= submit_tag "Generate", class: 'insult-button' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title or "Bioluminous" %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class="black-bg">

    <div id="main">
        <%= yield %>
    </div>

</body>
</html>

app/views/tabletop/libram.html.erb
<div>
    <p>Click below for a random magical effect.</p>
    <button id="le-button">Click me</button>
    <h1 id="results" style="color: purple;"></h1>
    <p><a href="https://centralia.aquest.com/downloads/NLRMEv2.pdf" target="_blank">Source</a></p>
    <script type="text/javascript">
    $(function() {
        $.get('/libram.txt', function(data) {
            const rows = data.trim().replace(/í/g, '\'').split('\n');
            $('#le-button').click(function(e) {
                var i = Math.trunc(Math.random() * rows.length);
                var text = rows[i].match(/^\d{4} (.+)$/)[1] + '.';
                $('#results').text(text);
            });
        });
    });
    </script>
</div>